
# CEL Processing Script for Forensic miRNA Analysis
# Auto-generated by cel_processor_final.py

# Set up
suppressPackageStartupMessages({
    if (!require("BiocManager", quietly = TRUE))
        install.packages("BiocManager", repos="https://cloud.r-project.org")
    
    packages_needed <- c("oligo", "Biobase")
    packages_installed <- installed.packages()[, "Package"]
    missing <- packages_needed[!packages_needed %in% packages_installed]
    
    if (length(missing) > 0) {
        cat("Installing missing packages:", missing, "\n")
        BiocManager::install(missing, ask = FALSE, update = FALSE)
    }
    
    library(oligo)
    library(Biobase)
})

# Set paths
cel_dir <- "data/raw/GSE49630_CEL"
output_dir <- "data/processed/cel"

# Create output directory
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# List CEL files
cel_files <- list.files(cel_dir, pattern = "\\.CEL\\.gz$", full.names = TRUE)
cat("Found", length(cel_files), "CEL files\n")

# Decompress files
temp_dir <- tempdir()
temp_files <- character(length(cel_files))

for (i in seq_along(cel_files)) {
    temp_file <- file.path(temp_dir, gsub("\\.gz$", "", basename(cel_files[i])))
    system2("gunzip", args = c("-c", cel_files[i]), stdout = temp_file)
    temp_files[i] <- temp_file
}

# Read CEL files
cat("Reading CEL files...\n")
raw_data <- read.celfiles(temp_files, verbose = FALSE)

# RMA normalization
cat("Performing RMA normalization...\n")
eset <- rma(raw_data, background = TRUE, normalize = TRUE)

# Extract expression matrix
expr_matrix <- exprs(eset)

# Clean sample names
sample_names <- gsub("\\.CEL$", "", basename(temp_files))
colnames(expr_matrix) <- sample_names

# Save expression matrix
output_file <- file.path(output_dir, "cel_raw_expression.csv")
write.csv(expr_matrix, output_file)
cat("Saved expression matrix to", output_file, "\n")

# Print summary
cat("\nProcessing complete!\n")
cat("Dimensions:", nrow(expr_matrix), "probes x", ncol(expr_matrix), "samples\n")
cat("Expression range:", range(expr_matrix), "\n")

# Clean up temp files
unlink(temp_files)
